### ISSUE TITLE
Validate Special Character in UserName

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-user#5]
Implement validation for special characters in the username when creating a new user.
you have to write TestFunction and test those dataset;

asd!^+.   -> False
Qwe123_ -> True

**Comment by Smnrgcl** [comment]
I was going to make these corrections, but the file that needed corrections came to me already corrected. So, I couldn't make any corrections.

**Comment by Sddilora** [comment]
Oh I just realized that the test cases are empty in the test field.
```go
		// TODO: Add test cases.
```
you need to handle that part.

**Comment by Sddilora** [comment]
I talked to our leader again and it seems that we misunderstood the task ( again :)). We are required to add the necessary rules for creating a username to the CheckUserName func, and then write the test for it.

![image](https://github.com/octoposprime/op-be-user/assets/122971619/49511628-f5b9-476d-99f7-daa7ac12ccaf)

In general, usernames typically have the following rules:
- Cannot contain spaces.
- Cannot contain special characters such as ! @ # $ % ^ & * ( ) - + = { } [ ] | \ : ; " ' < > , . ? / etc.
- May allow underscores (_) and periods (.) in some cases.

I searched on the internet but couldn't find all the rulesets for this in a collective manner. If you can do some research on this and share it with us under this issue, that would be great.
