### ISSUE TITLE
Remove Auth Layers from User Service (pkg)

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-user#56]
Remove authentication-related layers from the "pkg" layer of the User Service to organize the architecture.

**Comment by ebrarkesici** [comment]
I made the necessary changes in this branch: https://github.com/octoposprime/op-be-user/tree/bugfix/ebr/56/auth-file-deleted

**Comment by ebrarkesici** [comment]
I made the changes and open the pull request: https://github.com/octoposprime/op-be-user/pull/61.
