### ISSUE TITLE
The "companyId" field needs to be removed.

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-user#64]
https://github.com/octoposprime/op-be-user/blob/4fe7b2391de25d0fb80c4d6517dab5913d23b8dc/internal/domain/model/entity/userfilter.go#L37

The "companyId" field needs to be removed from "NewUserFilter" func

**Comment by arzuuddemir** [comment]
I removed companyId field.

**Comment by Sddilora** [comment]
you need to create a pull request from your fork

**Comment by Sddilora** [comment]
oh sorry, I have reviewed the PR and added a comment to it.
